In [20]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
import numpy as np
%matplotlib inline

def getData(balance_ones=True):
    # images are 60x12 = 720 size vectors
    X = []
    Y = []
    
    first = True
    for line in open('imgs_sample_1.csv'):
        if first:
            first = False
        else:
            row = line.split(',')
            X.append([float(p) for p in row[1].split(' ')])
            Y.append(int(row[0])) ##true lable
            
    X, Y = np.array(X), np.array(Y)
    #X = np.array(X)

    return X,Y

In [21]:
def main():   
    X,Y = getData()
    
    kmeans = KMeans(n_clusters=2, random_state=0).fit(X)
    label = kmeans.labels_
    print(kmeans.labels_)
    print(Y)
    return kmeans.labels_

In [22]:
if __name__ == '__main__':
    main()

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
 26 27 28 29 30 31 32]


In [23]:
### kmeans on sample 2
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
import numpy as np
%matplotlib inline

def getData(balance_ones=True):
    # images are 60x12 = 720 size vectors
    X = []
    Y = []
    
    first = True
    for line in open('imgs_sample_2.csv'):
        if first:
            first = False
        else:
            row = line.split(',')
            X.append([float(p) for p in row[1].split(' ')])
            Y.append(int(row[0])) ##true lable
            
    X, Y = np.array(X), np.array(Y)
    #X = np.array(X)

    return X,Y

def main():   
    X,Y = getData()
    
    kmeans = KMeans(n_clusters=2, random_state=0).fit(X)
    label = kmeans.labels_
    print(kmeans.labels_)
    print(Y[label])
    return kmeans.labels_

if __name__ == '__main__':
    main()

[0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0]
[1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 2 1 1 1 1 1 1 1 1 1 1 2 1 1 2 1 1]


In [24]:
### kmeans on sample 3
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
import numpy as np
%matplotlib inline

def getData(balance_ones=True):
    # images are 60x12 = 720 size vectors
    X = []
    Y = []
    
    first = True
    for line in open('imgs_sample_3.csv'):
        if first:
            first = False
        else:
            row = line.split(',')
            X.append([float(p) for p in row[1].split(' ')])
            Y.append(int(row[0])) ##true lable
            
    X, Y = np.array(X), np.array(Y)
    #X = np.array(X)

    return X,Y

def main():   
    X,Y = getData()
    
    kmeans = KMeans(n_clusters=2, random_state=0).fit(X)
    label = kmeans.labels_
    print(kmeans.labels_)
    print(Y[label])
    return kmeans.labels_

if __name__ == '__main__':
    main()

[0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0]
[1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 2 1 1 1 1 1 1 1 1 1 1 2 1 1 2 1 1]


In [25]:
### kmeans on sample 4
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
import numpy as np
%matplotlib inline

def getData(balance_ones=True):
    # images are 60x12 = 720 size vectors
    X = []
    Y = []
    
    first = True
    for line in open('imgs_sample_4.csv'):
        if first:
            first = False
        else:
            row = line.split(',')
            X.append([float(p) for p in row[1].split(' ')])
            Y.append(int(row[0])) ##true lable
            
    X, Y = np.array(X), np.array(Y)
    #X = np.array(X)

    return X,Y

def main():   
    X,Y = getData()
    
    kmeans = KMeans(n_clusters=2, random_state=0).fit(X)
    label = kmeans.labels_
    print(kmeans.labels_)
    print(Y[label])
    return kmeans.labels_

if __name__ == '__main__':
    main()

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1]


In [26]:
### kmeans on sample 5
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
import numpy as np
%matplotlib inline

def getData(balance_ones=True):
    # images are 60x12 = 720 size vectors
    X = []
    Y = []
    
    first = True
    for line in open('imgs_sample_5.csv'):
        if first:
            first = False
        else:
            row = line.split(',')
            X.append([float(p) for p in row[1].split(' ')])
            Y.append(int(row[0])) ##true lable
            
    X, Y = np.array(X), np.array(Y)
    #X = np.array(X)

    return X,Y

def main():   
    X,Y = getData()
    
    kmeans = KMeans(n_clusters=2, random_state=0).fit(X)
    label = kmeans.labels_
    print(kmeans.labels_)
    print(Y[label])
    return kmeans.labels_

if __name__ == '__main__':
    main()

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1]


In [27]:
### kmeans on sample 6
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
import numpy as np
%matplotlib inline

def getData(balance_ones=True):
    # images are 60x12 = 720 size vectors
    X = []
    Y = []
    
    first = True
    for line in open('imgs_sample_6.csv'):
        if first:
            first = False
        else:
            row = line.split(',')
            X.append([float(p) for p in row[1].split(' ')])
            Y.append(int(row[0])) ##true lable
            
    X, Y = np.array(X), np.array(Y)
    #X = np.array(X)

    return X,Y

def main():   
    X,Y = getData()
    
    kmeans = KMeans(n_clusters=2, random_state=0).fit(X)
    label = kmeans.labels_
    print(kmeans.labels_)
    print(Y[label])
    return kmeans.labels_

if __name__ == '__main__':
    main()

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1]


In [28]:
### kmeans on sample 7
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
import numpy as np
%matplotlib inline

def getData(balance_ones=True):
    # images are 60x12 = 720 size vectors
    X = []
    Y = []
    
    first = True
    for line in open('imgs_sample_7.csv'):
        if first:
            first = False
        else:
            row = line.split(',')
            X.append([float(p) for p in row[1].split(' ')])
            Y.append(int(row[0])) ##true lable
            
    X, Y = np.array(X), np.array(Y)
    #X = np.array(X)

    return X,Y

def main():   
    X,Y = getData()
    
    kmeans = KMeans(n_clusters=2, random_state=0).fit(X)
    label = kmeans.labels_
    print(kmeans.labels_)
    print(Y[label])
    return kmeans.labels_

if __name__ == '__main__':
    main()

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


## kmeans on sample 1 and 3

In [25]:
### kmeans on sample 1 and 3
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
import numpy as np
%matplotlib inline

def getData(balance_ones=True):
    # images are 60x12 = 720 size vectors
    X = []
    Y = []
    
    first = True
    for line in open('imgs_sample_1and3.csv'):
        if first:
            first = False
        else:
            row = line.split(',')
            X.append([float(p) for p in row[1].split(' ')])
            Y.append(int(row[0])) ##true lable
            
    X, Y = np.array(X), np.array(Y)
    #X = np.array(X)

    return X,Y

def main():   
    X,Y = getData()
    
    kmeans = KMeans(n_clusters=32, random_state=0).fit(X)
    label = kmeans.labels_
    print(kmeans.labels_)
    print(Y)
    return kmeans.labels_

if __name__ == '__main__':
    main()

[ 8  8 27 23 26 26  0 27 19 26 13 27 13 16 26  4 26 25 26 21 17  8  8  8  8
 20  2  8 26 10  3 26 26  8 13  9 19 27 27 12 18 28 29 13 28 11  8  1 26  7
  8 30 17 26 15 22 22 24  5 31 22  6 14 26]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
 26 27 28 29 30 31 32  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18
 19 20 21 22 23 24 25 26 27 28 29 30 31 32]


## k-means using imgs_sample data in 32 clusters

In [9]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
import numpy as np
%matplotlib inline

def getData(balance_ones=True):
    # images are 60x12 = 720 size vectors
    NUM = []  #1 - 32
    SAMPLE = []  #7
    X = []  #32*7
    
    first = True
    for line in open('all_samples.csv'):
        if first:
            first = False
        else:
            row = line.split(',')
            NUM.append(int(row[0]))  #cell number
            SAMPLE.append(int(row[1]))  #sample number
            X.append([float(p) for p in row[2].split(' ')])
            
    NUM, SAMPLE, X = np.array(NUM), np.array(SAMPLE), np.array(X)
    #X = np.array(X)

    return NUM, SAMPLE, X



In [10]:
def main():   
    NUM, SAMPLE, X = getData()
    
    kmeans = KMeans(n_clusters=32, random_state=0).fit(X)
    label = kmeans.labels_
    print(kmeans.labels_)
    print(NUM)
    np.savetxt('/Users/shuixinjiang/Desktop/DATS6203/Final/imgs_kmeans.csv',kmeans.labels_,delimiter=',')

    return kmeans.labels_

if __name__ == '__main__':
    main()

[ 0  0 31 11  0  0 31 31 11  0 31 31 31 12  0  3  0 30  0 30 30  0  0  0  0
 30 27  0  0  5 18  0  0  0  0 31  0  0  0  0 31  0  0  0 31 25  0 12  0 30
  0  0 30  0  0  0  0 15 23  0  0 28  0  0  0  0 31 12 11 31 31 11 25 11 11
 31 11 21 31 17  0 23  0 30 30  0 15 31 31 23 13 15 31  6 24  0  0  0  0 31
  0  0 30 11 19  0 25 11 11 27  0  9 31 28 31 23 28 15 15 15 31 14  1 15 31
 16 26  0  0  0  0 31  0  0 15 11 19  0 25 11 11 27  0  7  0 23  0 30 23 31
 15 31 31 23 10 15  0  0 24  0  0  0  0 31  0  0 11 11 19  0 25 11 11  2  0
  4 31 14 31 23 14 15 15 15 31 14  8 15 31 20 29  0  0  0  0 31  0  0 31 31
 25  0 31  0 31 11  0 22  0 30  0 31 31  0  0  0  0 31 28  0  0 15  0  0]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
 26 27 28 29 30 31 32  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18
 19 20 21 22 23 24 25 26 27 28 29 30 31 32  1  2  3  4  5  6  7  8  9 10 11
 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32  1  2  3  4
  5  6  7  8  

## k-means using imgs_sample data in 8 clusters

In [15]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
import numpy as np
%matplotlib inline

def getData(balance_ones=True):
    # images are 60x12 = 720 size vectors
    NUM = []  #1 - 32
    SAMPLE = []  #7
    X1 = []  #32*7
    X2 = []  #32*7
    
    first = False
    for line in open('pca_data.csv'):
        if first:
            first = True
        else:
            row = line.split(',')
            NUM.append(int(row[2]))  #cell number
            SAMPLE.append(int(row[3]))  #sample number
            X1.append([float(p) for p in row[0].split(' ')])
            X2.append([float(p) for p in row[1].split(' ')])
            
    NUM, SAMPLE, X1, X2 = np.array(NUM), np.array(SAMPLE), np.array(X1), np.array(X2)
    #X = np.array(X)

    return NUM, SAMPLE, X1, X2

def main():   
    NUM, SAMPLE, X1, X2 = getData()
    
    kmeans = KMeans(n_clusters=8, random_state=0).fit(X1, X2)
    label = kmeans.labels_
    print(kmeans.labels_)
    print(NUM)
    np.savetxt('/Users/shuixinjiang/Desktop/DATS6203/Final/pca_kmeans8.csv',kmeans.labels_,delimiter=',')

    return kmeans.labels_

if __name__ == '__main__':
    main()

[0 0 0 7 0 0 4 7 4 0 0 7 7 6 0 6 0 2 0 2 2 7 0 0 7 2 6 0 0 5 3 0 0 0 0 0 0
 0 0 7 7 0 0 0 7 4 0 4 0 2 0 0 2 7 0 0 0 2 4 0 0 5 0 0 0 0 0 4 7 0 4 7 4 7
 7 0 7 1 0 5 0 2 0 4 4 0 7 7 7 2 1 7 7 3 1 0 0 0 0 0 0 0 2 7 2 0 7 7 4 5 0
 5 7 6 7 2 2 7 4 7 7 6 3 4 7 3 1 0 0 0 0 0 0 0 2 7 2 0 7 7 7 6 0 1 0 2 0 4
 4 7 7 7 7 2 3 7 0 0 5 0 0 0 0 0 0 0 2 7 6 0 4 7 7 5 0 1 7 6 0 4 2 7 4 7 7
 6 3 4 7 3 1 0 0 0 0 0 0 0 4 7 4 0 0 0 0 4 0 2 0 4 0 7 7 0 0 7 0 4 6 0 0 6
 0 0]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
 26 27 28 29 30 31 32  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18
 19 20 21 22 23 24 25 26 27 28 29 30 31 32  1  2  3  4  5  6  7  8  9 10 11
 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32  1  2  3  4
  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29
 30 31 32  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22
 23 24 25 26 27 28 29 30 31 32  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15
 16 17 18 19

## k-means using post-pca data 224 rows * 2 features

In [16]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
import numpy as np
%matplotlib inline

def getData(balance_ones=True):
    # images are 60x12 = 720 size vectors
    NUM = []  #1 - 32
    SAMPLE = []  #7
    X1 = []  #32*7
    X2 = []  #32*7
    
    first = False
    for line in open('pca_data.csv'):
        if first:
            first = True
        else:
            row = line.split(',')
            NUM.append(int(row[2]))  #cell number
            SAMPLE.append(int(row[3]))  #sample number
            X1.append([float(p) for p in row[0].split(' ')])
            X2.append([float(p) for p in row[1].split(' ')])
            
    NUM, SAMPLE, X1, X2 = np.array(NUM), np.array(SAMPLE), np.array(X1), np.array(X2)
    #X = np.array(X)

    return NUM, SAMPLE, X1, X2

In [17]:
def main():   
    NUM, SAMPLE, X1, X2 = getData()
    
    kmeans = KMeans(n_clusters=32, random_state=0).fit(X1, X2)
    label = kmeans.labels_
    print(kmeans.labels_)
    print(NUM)
    np.savetxt('/Users/shuixinjiang/Desktop/DATS6203/Final/pca_kmeans.csv',kmeans.labels_,delimiter=',')

    return kmeans.labels_

if __name__ == '__main__':
    main()

[ 0 14 23 29 14 14 25 29  4  0 23 11 29 12  0 24 14  3 16 22 22 11  0 16 11
 28 12 16 16 20  2  0 14 14 23 16 14 27 27 11 31 27 16 16 29 25  0 25 14  3
 27 27 22 11  0 16 27  3 19 16 16 15 27 27 14 14 23 18  6 23 19 30  9 30 31
 23 30  5 16 20  0 22 16 25 25 23 31 29  6  3 13 18 11  8 17 16 14 14 16  0
 14  0  3 30  3  0 30  6 18 26  0  1 11 24 11 22 28  6 18  6  6 24  8  4 11
 21 13 16 14 14 16  0 14 14 22  6  3  0 31  6  6 15  0 17 16  3 16  4  9 29
 30  6 29 28  8 30 23 27 20 16 14 14 16  0 14  0 28 18 12  0 18  6 18 20  0
  5 11  7 23 25  3 30  4 30 30  7 10 19 11 21 17 23 14 14 16  0 14 14 19 11
  4  0 23 16 23 19 27 28 16 25 27  6 30 23  0 29 23  9 12 16 16  7 27 27]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
 26 27 28 29 30 31 32  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18
 19 20 21 22 23 24 25 26 27 28 29 30 31 32  1  2  3  4  5  6  7  8  9 10 11
 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32  1  2  3  4
  5  6  7  8  